### ISSUE TITLE
Option "tpm_resetdalock -x" doesn't appear

### ISSUE THREAD

**Issue by edigley** [opencit/opencit-contrib#1]
After installing the patch, the additional flag "-x" is not available.

I've downloaded the opencit-contrib-master.zip, unziped it and run:
       ./install-patched-tpm-tools.bin

After an apparently succesful installation, there isn't such an option:
# tpm_resetdalock -x

tpm_resetdalock: invalid option -- 'x'
Usage: tpm_resetdalock [options]
    -h, --help
        Display command usage info.
    -v, --version
        Display command version info.
    -l, --log [none|error|info|debug]
        Set logging level.
    -z, --well-known
        Use TSS_WELL_KNOWN_SECRET (20 zero bytes) as the owner secret.

Thank you

**Comment by ZahediAquino** [comment]
My first guess is that you have tpm-tools and tpm-patched-tools installed. Can you try to uninstall tpm-tools and then just install the patched tools?

**Comment by edigley** [comment]
I've uninstalled tpm-tools and also trousers. Then I've downloaded the opencit-contrib-master.zip, unziped it and run:

```
./install-patched-tpm-tools.bin
```

The aforementioned packages have been installed.

Once again, no indicative that the patch has been installed.

**Comment by ZahediAquino** [comment]
Can you please check this location after installing patched tools?

`/usr/local/sbin/`

You should see tpm_\* commands... run:
`/usr/local/sbin/tpm_nvwrite --help`

You should get:

```
 -x, --use-hex
                Use hex encoding for TPM owner secret or NVRAM area secret
```

**Comment by edigley** [comment]
I checked the directory and the command As you said, I could confirm:
    -x, --use-hex
        Use hex encoding for TPM owner secret or NVRAM area secret

For some reason, the tpm_resetdalock doesn't shows the -x option.

$ /usr/local/sbin/tpm_resetdalock --help
Usage: /usr/local/sbin/tpm_resetdalock [options]
    -h, --help
        Display command usage info.
    -v, --version
        Display command version info.
    -l, --log [none|error|info|debug]
        Set logging level.
    -z, --well-known
        Use TSS_WELL_KNOWN_SECRET (20 zero bytes) as the owner secret.

I am trying to install opencit agent, but everytime I run de install script, after clear the tpm in BIOS, I got an "our TPM is defending against dictionaly attacks".
I Thought the patch had some issue.

Anyway, thank you very much for your help.

**Comment by ZahediAquino** [comment]
Issue is generally using TPM commands with an invalid owner password.  Cause for that can be varied.  

DA lockout implementation is different for different TPM manufacturers.  Some support the resetdalock command but some don’t.  In some cases you just have to wait up to 48 hrs for the lock to clear.

**Comment by edigley** [comment]
You're right. After around 2 days i could owner the tpm again.

After uninstalling the oficial tpm-tools and trousers and letting the patch install these dependencies the the opencit agent finally has been installed successfully.

Thank you again for your help.

**Comment by ZahediAquino** [comment]
Awesome! Closing the issue then.
